name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v4
   
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
   
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov PyYAML
        python -m pip install -e .
   
    - name: Run tests (non-Windows)
      if: matrix.os != 'windows-latest'
      run: |
        pytest tests --cov=latex_to_llm --cov-report=xml
        
    - name: Run tests (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        python run_tests.py --quiet --verbose
   
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
   
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
   
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 black isort
   
    - name: Lint with flake8
      run: |
        flake8 latex_to_llm.py tests
   
    - name: Check formatting with black
      run: |
        black --check latex_to_llm.py tests
   
    - name: Check imports with isort
      run: |
        isort --check-only latex_to_llm.py tests